-- Create "teams" table
CREATE TABLE "teams" ("id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, "slug" text NOT NULL, "name" text NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "teams_slug_key" UNIQUE ("slug"), CONSTRAINT "teams_name_check" CHECK ((name = btrim(name)) AND ((char_length(name) >= 1) AND (char_length(name) <= 100))), CONSTRAINT "teams_slug_format_check" CHECK (slug ~ '^[a-z][a-z0-9-]{0,62}$'::text), CONSTRAINT "teams_updated_at_check" CHECK (updated_at >= created_at));
-- Create "services" table
CREATE TABLE "services" ("id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, "team_id" bigint NOT NULL, "slug" text NOT NULL, "name" text NOT NULL, "description" text NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "services_team_id_slug_key" UNIQUE ("team_id", "slug"), CONSTRAINT "services_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT, CONSTRAINT "services_description_length_check" CHECK ((description IS NULL) OR (char_length(description) <= 500)), CONSTRAINT "services_name_check" CHECK ((name = btrim(name)) AND ((char_length(name) >= 1) AND (char_length(name) <= 100))), CONSTRAINT "services_slug_format_check" CHECK (slug ~ '^[a-z][a-z0-9-]{0,62}$'::text), CONSTRAINT "services_updated_at_check" CHECK (updated_at >= created_at));
-- Create index "services_team_id_id_idx" to table: "services"
CREATE INDEX "services_team_id_id_idx" ON "services" ("team_id", "id");
-- Create "environments" table
CREATE TABLE "environments" ("id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, "service_id" bigint NOT NULL, "slug" text NOT NULL, "name" text NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "environments_service_id_slug_key" UNIQUE ("service_id", "slug"), CONSTRAINT "environments_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "services" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT, CONSTRAINT "environments_name_check" CHECK ((name = btrim(name)) AND ((char_length(name) >= 1) AND (char_length(name) <= 100))), CONSTRAINT "environments_slug_format_check" CHECK (slug ~ '^[a-z][a-z0-9-]{0,62}$'::text), CONSTRAINT "environments_updated_at_check" CHECK (updated_at >= created_at));
-- Create index "environments_service_id_id_idx" to table: "environments"
CREATE INDEX "environments_service_id_id_idx" ON "environments" ("service_id", "id");
