// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environments.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (service_id, slug, name)
VALUES ($1, $2, $3)
RETURNING id, service_id, slug, name, created_at, updated_at
`

type CreateEnvironmentParams struct {
	ServiceID int64
	Slug      string
	Name      string
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment, arg.ServiceID, arg.Slug, arg.Name)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEnvironment = `-- name: DeleteEnvironment :one
DELETE FROM environments
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteEnvironment(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteEnvironment, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getEnvironmentByID = `-- name: GetEnvironmentByID :one
SELECT id, service_id, slug, name, created_at, updated_at
FROM environments
WHERE id = $1
`

func (q *Queries) GetEnvironmentByID(ctx context.Context, id int64) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByID, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnvironmentsAfterCursor = `-- name: ListEnvironmentsAfterCursor :many
SELECT id, service_id, slug, name, created_at, updated_at
FROM environments
WHERE created_at < $1
  OR (created_at = $1 AND id < $2)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListEnvironmentsAfterCursorParams struct {
	CreatedAt pgtype.Timestamptz
	ID        int64
	Limit     int32
}

func (q *Queries) ListEnvironmentsAfterCursor(ctx context.Context, arg ListEnvironmentsAfterCursorParams) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsAfterCursor, arg.CreatedAt, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentsAfterCursorByServiceID = `-- name: ListEnvironmentsAfterCursorByServiceID :many
SELECT id, service_id, slug, name, created_at, updated_at
FROM environments
WHERE service_id = $1
  AND (
    created_at < $2
    OR (created_at = $2 AND id < $3)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListEnvironmentsAfterCursorByServiceIDParams struct {
	ServiceID int64
	CreatedAt pgtype.Timestamptz
	ID        int64
	Limit     int32
}

func (q *Queries) ListEnvironmentsAfterCursorByServiceID(ctx context.Context, arg ListEnvironmentsAfterCursorByServiceIDParams) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsAfterCursorByServiceID,
		arg.ServiceID,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentsByServiceID = `-- name: ListEnvironmentsByServiceID :many
SELECT id, service_id, slug, name, created_at, updated_at
FROM environments
WHERE service_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListEnvironmentsByServiceID(ctx context.Context, serviceID int64) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsByServiceID, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentsFirstPage = `-- name: ListEnvironmentsFirstPage :many
SELECT id, service_id, slug, name, created_at, updated_at
FROM environments
ORDER BY created_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListEnvironmentsFirstPage(ctx context.Context, limit int32) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsFirstPage, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentsFirstPageByServiceID = `-- name: ListEnvironmentsFirstPageByServiceID :many
SELECT id, service_id, slug, name, created_at, updated_at
FROM environments
WHERE service_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListEnvironmentsFirstPageByServiceIDParams struct {
	ServiceID int64
	Limit     int32
}

func (q *Queries) ListEnvironmentsFirstPageByServiceID(ctx context.Context, arg ListEnvironmentsFirstPageByServiceIDParams) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsFirstPageByServiceID, arg.ServiceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnvironment = `-- name: UpdateEnvironment :one
UPDATE environments
SET slug = COALESCE($1::text, slug),
    name = COALESCE($2::text, name),
    updated_at = now()
WHERE id = $3
RETURNING id, service_id, slug, name, created_at, updated_at
`

type UpdateEnvironmentParams struct {
	Slug pgtype.Text
	Name pgtype.Text
	ID   int64
}

func (q *Queries) UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, updateEnvironment, arg.Slug, arg.Name, arg.ID)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
