// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createService = `-- name: CreateService :one
INSERT INTO services (team_id, slug, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, team_id, slug, name, description, created_at, updated_at
`

type CreateServiceParams struct {
	TeamID      int64
	Slug        string
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.TeamID,
		arg.Slug,
		arg.Name,
		arg.Description,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :one
DELETE FROM services
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteService(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteService, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, team_id, slug, name, description, created_at, updated_at
FROM services
WHERE id = $1
`

func (q *Queries) GetServiceByID(ctx context.Context, id int64) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServicesAfterCursor = `-- name: ListServicesAfterCursor :many
SELECT id, team_id, slug, name, description, created_at, updated_at
FROM services
WHERE created_at < $1
  OR (created_at = $1 AND id < $2)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListServicesAfterCursorParams struct {
	CreatedAt pgtype.Timestamptz
	ID        int64
	Limit     int32
}

func (q *Queries) ListServicesAfterCursor(ctx context.Context, arg ListServicesAfterCursorParams) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesAfterCursor, arg.CreatedAt, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesAfterCursorByTeamID = `-- name: ListServicesAfterCursorByTeamID :many
SELECT id, team_id, slug, name, description, created_at, updated_at
FROM services
WHERE team_id = $1
  AND (
    created_at < $2
    OR (created_at = $2 AND id < $3)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListServicesAfterCursorByTeamIDParams struct {
	TeamID    int64
	CreatedAt pgtype.Timestamptz
	ID        int64
	Limit     int32
}

func (q *Queries) ListServicesAfterCursorByTeamID(ctx context.Context, arg ListServicesAfterCursorByTeamIDParams) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesAfterCursorByTeamID,
		arg.TeamID,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesFirstPage = `-- name: ListServicesFirstPage :many
SELECT id, team_id, slug, name, description, created_at, updated_at
FROM services
ORDER BY created_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListServicesFirstPage(ctx context.Context, limit int32) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesFirstPage, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesFirstPageByTeamID = `-- name: ListServicesFirstPageByTeamID :many
SELECT id, team_id, slug, name, description, created_at, updated_at
FROM services
WHERE team_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListServicesFirstPageByTeamIDParams struct {
	TeamID int64
	Limit  int32
}

func (q *Queries) ListServicesFirstPageByTeamID(ctx context.Context, arg ListServicesFirstPageByTeamIDParams) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesFirstPageByTeamID, arg.TeamID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET slug = COALESCE($1::text, slug),
    name = COALESCE($2::text, name),
    description = CASE
      WHEN $3::boolean
        THEN $4::text
      ELSE description
    END,
    updated_at = now()
WHERE id = $5
RETURNING id, team_id, slug, name, description, created_at, updated_at
`

type UpdateServiceParams struct {
	Slug                pgtype.Text
	Name                pgtype.Text
	DescriptionProvided bool
	Description         pgtype.Text
	ID                  int64
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.Slug,
		arg.Name,
		arg.DescriptionProvided,
		arg.Description,
		arg.ID,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
